"""Install a prepared Maia Meet release behind the existing Apps nginx site."""
import argparse
import datetime
import ipaddress
import os
from pathlib import Path
import pwd
import re
import shutil
import socket
import subprocess
import time
import urllib.request

parser = argparse.ArgumentParser()
parser.add_argument('--bundle', required=True, type=Path)
parser.add_argument('--port', type=int, default=3081)
parser.add_argument('--domain', default='apps.maiaplatform.org')
parser.add_argument('--site', type=Path, default=Path('/etc/nginx/sites-available/apps.maiaplatform.org.conf'))
parser.add_argument('--dedicated', action='store_true')
parser.add_argument('--bind', default='10.77.0.2')
parser.add_argument('--meet-domain', default='meet.maiaplatform.org')
parser.add_argument('--prepare', action='store_true')
args = parser.parse_args()
if not 1 <= args.port <= 65535 or not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9.-]+', args.domain):
    parser.error('Invalid port or domain')
if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9.-]+', args.meet_domain):
    parser.error('Invalid Meet domain')
if args.dedicated:
    address = ipaddress.IPv4Address(args.bind)
    if not address.is_private or address.is_unspecified or address.is_loopback:
        parser.error('--bind must be the private IPv4 address of the VPN interface')
bind_host = args.bind if args.dedicated else '127.0.0.1'
base_path = '/' if args.dedicated else '/maia-meet/'
public_url = f'https://{args.meet_domain}/' if args.dedicated else f'https://{args.domain}/maia-meet/'
args.bundle = args.bundle.resolve()
args.site = args.site.resolve(strict=True)
if not args.site.is_relative_to('/etc/nginx'):
    parser.error('Site must be under /etc/nginx')
base = Path('/opt/maia-meet')
current = base / 'current'
env_path = Path('/etc/maia-meet/meet.env')
unit_path = Path('/etc/systemd/system/maia-meet-signaling.service')
snippet = Path('/etc/nginx/maia-apps.d/maia-meet.conf')
include = 'include /etc/nginx/maia-apps.d/*.conf;'
service = 'maia-meet-signaling'


def run(*command, **kwargs):
    return subprocess.run(command, check=True, **kwargs)


def site_config():
    original = args.site.read_text()
    if re.search(r'managed by.*maia.edge|generated by.*maia.edge', original, re.I):
        raise RuntimeError('Use the Maia Edge CLI for a managed site; this installer expects the Apps template')
    if len(re.findall(r'\bserver\s*\{', original)) != 1:
        raise RuntimeError('Expected exactly one Apps server block')
    if not re.search(r'\bserver_name\s+' + re.escape(args.domain) + r'\s*;', original):
        raise RuntimeError('The selected site does not match the Apps domain')
    if re.search(r'\blocation\s+(?:[=~^*]+\s+)?/maia-meet', original):
        raise RuntimeError('An existing Meet location needs manual review')
    if include in original:
        return original
    return re.sub(r'(\bserver\s*\{)', r'\1\n    ' + include, original, count=1)


location = f'''# Maia Meet: managed by deploy/install-apps.sh
location = /maia-meet {{ return 308 /maia-meet/$is_args$args; }}
location ^~ /maia-meet/ {{
    proxy_pass http://127.0.0.1:{args.port};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;
}}
'''
if args.dedicated:
    location = f"""# Maia Meet: managed by deploy/install-apps.sh
location = /maia-meet {{ return 308 https://{args.meet_domain}/$is_args$args; }}
location ^~ /maia-meet/ {{ return 308 https://{args.meet_domain}/$is_args$args; }}
"""
unit = '''[Unit]
Description=Maia Meet for Maia Apps
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=maia
Group=maia
WorkingDirectory=/opt/maia-meet/current/signaling
Environment=NODE_ENV=production
EnvironmentFile=/etc/maia-meet/meet.env
ExecStart=/usr/bin/node src/server.js
Restart=on-failure
RestartSec=2
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true

[Install]
WantedBy=multi-user.target
'''
proposed_site = site_config()
for path, content in [('maia-meet.conf', location), ('apps-site.conf', proposed_site), ('maia-meet-signaling.service', unit)]:
    (args.bundle / path).write_text(content)
if args.prepare:
    print(f'Validated plan: {bind_host}:{args.port}{base_path} -> {public_url}')
    raise SystemExit(0)
if os.geteuid() != 0:
    parser.error('Activation requires sudo; run the command printed by --prepare-only')
if current.exists() and not current.is_symlink():
    raise RuntimeError('/opt/maia-meet/current is not a release symlink')
if snippet.exists() and 'managed by deploy/install-apps.sh' not in snippet.read_text():
    raise RuntimeError('Refusing to overwrite an unmanaged Meet nginx snippet')
run('/usr/sbin/nginx', '-t')
pwd.getpwnam('maia')  # Existing Maia service account; do not silently reuse another user.
source_env = env_path if env_path.exists() else args.bundle / 'meet.env'
text = source_env.read_text()
# Preserve ICE/TURN credentials and other settings, overriding only the route.
text = '\n'.join(line for line in text.splitlines() if not re.match(r'\s*(?:export\s+)?(?:HOST|PORT|BASE_PATH|ALLOWED_ORIGINS)\s*=', line))
text += f'\nHOST={bind_host}\nPORT={args.port}\nBASE_PATH={base_path}\nALLOWED_ORIGINS={public_url.rstrip(chr(47))}\n'
prepared_env = args.bundle / 'installed.env'
prepared_env.write_text(text)
prepared_env.chmod(0o600)
# Validate without disclosing environment contents.
clean_env = {key: value for key, value in os.environ.items() if key not in ('HOST', 'PORT', 'BASE_PATH', 'ICE_SERVERS', 'ICE_TRANSPORT_POLICY', 'MAX_PARTICIPANTS', 'MAX_MESSAGE_BYTES', 'RATE_LIMIT_MESSAGES', 'ALLOWED_ORIGINS')}
run('/usr/bin/node', '--env-file=' + str(prepared_env), '--input-type=module', '-e',
    "await import('./src/config.js')", cwd=args.bundle / 'release/signaling', env=clean_env)

stamp = datetime.datetime.now().strftime('%Y%m%d-%H%M%S-%f')
backup = Path('/var/backups/maia-meet') / stamp
backup.mkdir(parents=True, mode=0o700)
backup.chmod(0o700)
paths = [args.site, snippet, unit_path, env_path]
previous = {}
for index, path in enumerate(paths):
    previous[path] = path.exists()
    if path.exists():
        shutil.copy2(path, backup / str(index))
(backup / 'paths.txt').write_text('\n'.join(f'{i}: {p}' for i, p in enumerate(paths)))
old_link = os.readlink(current) if current.is_symlink() else None
(backup / 'previous-release.txt').write_text(old_link or '')
was_active = subprocess.run(['systemctl', 'is-active', '--quiet', service]).returncode == 0
was_enabled = subprocess.run(['systemctl', 'is-enabled', '--quiet', service]).returncode == 0
if not was_active:
    with socket.socket() as probe:
        probe.bind((bind_host, args.port))
release = base / 'releases' / stamp
try:
    shutil.copytree(args.bundle / 'release', release)
    base.chmod(0o755)
    (base / 'releases').chmod(0o755)
    # Source checkout and temporary files may have private user permissions.
    for root, dirs, files in os.walk(release):
        os.chmod(root, 0o755)
        for name in files:
            os.chmod(Path(root) / name, 0o644)
    if current.is_symlink():
        current.unlink()
    current.symlink_to(release)
    for path in [snippet, unit_path, env_path]:
        path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(text)
    env_path.chmod(0o600)
    unit_path.write_text(unit)
    snippet.write_text(location)
    args.site.write_text(proposed_site)
    run('/usr/sbin/nginx', '-t')
    run('systemctl', 'daemon-reload')
    run('systemctl', 'restart', service)
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    for attempt in range(50):
        try:
            with opener.open(f'http://{bind_host}:{args.port}{base_path}health', timeout=1) as response:
                if response.status == 200:
                    break
        except OSError:
            time.sleep(0.2)
    else:
        raise RuntimeError('Meet health check failed')
    run('systemctl', 'is-active', '--quiet', service)
    run('systemctl', 'enable', service)
    run('systemctl', 'reload', 'nginx')
except Exception:
    subprocess.run(['systemctl', 'stop', service])
    if current.is_symlink():
        current.unlink()
    if old_link:
        current.symlink_to(old_link)
    for index, path in enumerate(paths):
        if previous[path]:
            shutil.copy2(backup / str(index), path)
        elif path.exists():
            path.unlink()
    if not was_enabled:
        subprocess.run(['systemctl', 'disable', service])
    subprocess.run(['systemctl', 'daemon-reload'])
    if was_active:
        subprocess.run(['systemctl', 'start', service])
    subprocess.run(['/usr/sbin/nginx', '-t'])
    subprocess.run(['systemctl', 'reload', 'nginx'])
    print(f'Installation failed; restored previous files. Backup: {backup}')
    raise
print(f'Installed node for: {public_url}')
print(f'Backend health: http://{bind_host}:{args.port}{base_path}health')
print(f'Configuration: {env_path}; restart {service} after changes.')
print(f'Backup: {backup}; release: {release}')
